# 项目基本信息
sonar.projectKey=home-assistant-core
sonar.projectName=home-assistant-core
sonar.projectVersion=1.0

# 源码路径
sonar.sources=./homeassistant/

# Python 相关
sonar.language=py
sonar.python.version=3

# 可选：排除测试目录
sonar.exclusions=./tests/

# 服务器地址和登录令牌
sonar.host.url=http://localhost:9000
sonar.token=sqa_7af6c687e1fff086882009b2d46f9589a1674442
